### ISSUE TITLE
[Request] Auto Sort - Sort by Tradeable/Untradeable

### ISSUE THREAD

**Issue by Ferikisekai** [Haselnussbomber/HaselTweaks#104]
For better inventory management.

**Comment by Haselnussbomber** [comment]
This is not something I can add, since I don't implement any sorting algorithms.
The tweak uses the games [/itemsort](https://eu.finalfantasyxiv.com/lodestone/playguide/db/text_command/a3840353abb/) command and that does not have the option to sort for tradeable/untradeable items.

Maybe SortaKinda (on Dalamuds main repo) can do this.
