### ISSUE TITLE
[Portrait Helper] Game crash on changing or saving gear set

### ISSUE THREAD

**Issue by Lapidearum** [Haselnussbomber/HaselTweaks#109]
The game immediately and consistently crashes (without even the "restart Dalamud" window opening!) when I attempt to switch between or alter gear sets with the Portrait Helper tweak active. With the tweak disabled, it works fine.

**Comment by RSPadilha** [comment]
We cannot switch to pictomancer or viper.
When it go to crafters, it selects 2 jobs down of what you clicked (the two new jobs missing in the array?). And if clicking Alchemist or Culinarian, it overflows and the game crash.

**Comment by Moonlight-Everlit** [comment]
Same thing here - crash on switching to any class.

**Comment by Haselnussbomber** [comment]
Sorry, guys! I finally found the issue: not allocating enough space for the new dyes and C# not crashing in my debug build. Fun!
It's fixed with [v24.1.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v24.1.1), so please update. 🙂
Thanks for reporting everyone!

---

@RSPadilha Thank you too. I've disabled the Character Class Switcher for now until I find a solution for that.
