### ISSUE TITLE
Portrait Helper generates invalid link in chat

### ISSUE THREAD

**Issue by Zumurrud** [Haselnussbomber/HaselTweaks#111]
![image](https://github.com/Haselnussbomber/HaselTweaks/assets/100747704/fed1b369-3abf-47ef-8d67-de3d65a79deb)

I had created a portrait for weaver.  I then got new gear and equipped it, as shown in the image.  The last line highlights as usual, seeming to indicate that it's a link, but clicking on it has no result.

Separately, updating the gear for machinist and clicking the generated link in chat opens the portrait editor for one of the crafting classes.  I have no idea what to make of that.

Most jobs work as expected.

**Comment by Haselnussbomber** [comment]
The link will open the portrait for the currently equipped gear set, so maybe you linked it wrong or accidentally have overwritten a gearset?!

**Comment by Haselnussbomber** [comment]
I moved my gearsets around, set them to 80 and whatnow, and I just don't run into this problem.
Sorry, but I don't know what's wrong.

**Comment by Zumurrud** [comment]
I got nothin' either.  For the time being, I have worked around the issue by recreating every gearset that wasn't working, following on from your suggestion of creating a new gearset to possibly fix some leftover cruft.

Thanks for taking a look at the problem!

**Comment by Zumurrud** [comment]
A friend of mine that I recommended this plugin to was having a similar problem!  Her SGE gearset consistently opens a different job's portrait (she had to go offline, so she hasn't tried any troubleshooting).  That prompted me to start fiddling with it again and I noticed something interesting that relates to the MCH behavior I reported in my first comment:

![image](https://github.com/user-attachments/assets/1e45ffbb-92a8-40cc-837d-1ce1d0f79556)

Look at the gearset Portrait Helper reports for this white mage portrait.  I _used_ to have a paladin gearset called PLD Bozja but deleted it long ago.  It kinda looks like its ghost is somehow occupying slot 40??

If I break this gearset's portrait and click the link in chat, nothing happens.

![image](https://github.com/user-attachments/assets/55a4d506-69dc-4ca8-86cc-074fba5a450d)

But if I renumber the gearset, Portrait Helper reports its name correctly, and breaking the portrait gets a correct link.

**Comment by Haselnussbomber** [comment]
I don't know what else to say other than recreate the gearsets. I don't have this problem so I can't fix it. 🤷‍♂️

**Comment by Haselnussbomber** [comment]
I might've found something.
It seems like it resolves the gearset id somehow before opening the window, so I'm now calling that function instead.
I don't know what it is or how it works, but it still works for me and if it works for you even better.
Please check it out with [v25.1.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.1.2)!

(I'm going to sleep now, it's 6 am, just so you know you don't need to hurry with testing. 😴)

**Comment by Zumurrud** [comment]
25.1.2 has fixed the problem!  Fantastic work.

Interestingly, the Portrait Helper bar can still show the name of some other gearset despite the link properly opening the current gearset's portrait; presumably the bar is not calling the translation function you found.  But this doesn't impede the user at all.

**Comment by Zumurrud** [comment]
**The actual usability problem - link can open the wrong portrait - is fixed, and please feel free to close the issue.**

In fact I had found a set of reproduction steps on 25.1.1 before getting the update (turns out you have to ask Dalamud to autoupdate plugins outside the main repo).  These steps differ from my original stabs in the dark, in that they can recreate the problem with brand-new gearsets.  I now speculate that the strange behavior occurs if you have a gap in the gearset numbers _and also_ you deleted a gearset at some point.

The behavior is the same on 25.1.1 and 25.1.2 except where noted.

- Create gearset A of some job (which becomes the last gearset in your list)
- Create gearset B of some different job (the new last gearset in your list)
- Create a portrait for B
- Delete A
  -> this leaves a gap in the gear set list numbers
- Right-click B in the gear set list and 'Edit Portrait'
- **Portrait Helper bar shows the gearset name of just-deleted A!**
- Exit editor
- Update B in order to generate a Portrait Helper link in chat
- Click link, which opens the correct portrait
  -> on 25.1.1, this link did nothing - exactly the problem I first reported

**Comment by Haselnussbomber** [comment]
Thank you for your reproduction steps! That really helps a lot because I can actually reproduce it. 😂 
I will fix the menu bar soon, but have to look into it more to understand what the game is actually doing in that function. 🙂

**Comment by Haselnussbomber** [comment]
Okay, I understand now what's happening.

For better illustration, I made a new gearset and moved it to number 51.
Internally, because of zero-based arrays, the Index in the array, as well as the Id field inside the entry, are 50.

![Screenshot1](https://github.com/user-attachments/assets/ad7b4771-d457-4938-aa25-21f79508b92b)

So far, so good.

The problem though is how the portrait editor handles gearsets.
It doesn't take the index in the list of gearsets (which would be 50).
Instead, it takes the list of gearsets and filters out all disabled entries (whether they haven't been created at all, or were deleted).
As you can see in the screenshot above, I have 44 gearsets. If you zero-base this list, the last entry will be at index 43.
And that 43 is what is sent over to the portrait editor.
This number is what I'm reading to display the name of the gearset. But since I didn't know it filters the list, I'm now accessing the gearset list at the wrong index (43 instead of 50). And that's why the name is wrong, and the link didn't work previously.

What I found is that the gearset module is tracking this in a small array near the end.
This way I can resolve the filtered index to get the index in the original entries array.

![Screenshot2](https://github.com/user-attachments/assets/fcd48c1f-5fb5-47af-875d-607267c39438)

This probably also the reason why they blocked us out from editing the gearset list while the portrait editor is open, because the portrait editor wouldn't get informed about the new index. Ugh..

I'll release a fix soon! :)

**Comment by Haselnussbomber** [comment]
Should be fixed with [v25.2.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.0), 🙂

**Comment by Zumurrud** [comment]
My tests work as expected, and my friend reports that her SGE portrait links work as expected with no further action on her part.

Thanks again!
