### ISSUE TITLE
search Marketboards

### ISSUE THREAD

**Issue by Burle17** [Haselnussbomber/HaselTweaks#143]
i would really like if you open the marketboard with the marketboard search active, that the Inventory is also opened at the same time

(saves one klick or keystroke^^)

**Comment by Haselnussbomber** [comment]
Sounds like a neat idea, but since there are so many context menus from where it's possible to start a search on the marketboard, I can't possibly predict what the user intents to do. Opening the inventory every time you access the market board would probably be more annoying than it would be useful. And as you said, it's only one button press, so... no. 😅
