### ISSUE TITLE
Aether Current Helper gets wide

### ISSUE THREAD

**Issue by PapaSmurf-ML64** [Haselnussbomber/HaselTweaks#18]
Currently in Labyrinthos for the first time, after attuning to a certain aether current (don't remember which), the window expands to the full width of my display. If I toggle the box to hide unlocked current to off, it slowly shrinks back to normal, if I tick it back on, it grows again. If it's any help, the ones I have not yet attuned to are 3, 4, 8, 9, 10 and all the quest based ones.

**Comment by Haselnussbomber** [comment]
Ah, yeah... I know that bug. That happened before! Reported in issue #14. I thought I fixed it, but apparently not. 🤷‍♂️ :joy:

I would love to find a better solution, but sadly I'm currently not subscribed to the game, so I can't work on this plugin at all.
When 6.3 hits I'll make sure to check that window (again). 🙂

Maybe a game restart or attuning an additional aether current might help for now. 🤔

**Comment by Haselnussbomber** [comment]
Looking back, the other issue I mentioned was a bug with the button in the top right, which opens the games Aether Current window. Thats fixed since v0.7.3.

I finally got into the game with the free login campaign (they require 30 days without subscription^^), but I just can't reproduce this issue. I tried many things, but the window will only always shrink.

Nevertheless, I have a feeling it's a problem due to centering the distance column, because that's the only time (besides the button in the top right) I move the ImGui cursor based on `ImGui.GetContentRegionAvail()`.

I've added a new config option in v0.7.6 (just released) to toggle the centering of the distance column.
So, if you have this problem again, open /haseltweaks, go to the "Aether Current Helper" settings and uncheck "Center distance column". I hope that helps!
