### ISSUE TITLE
Armory Chest Auto-sort crashing with staging 235137c

### ISSUE THREAD

**Issue by kynetical** [Haselnussbomber/HaselTweaks#19]
[dalamud.log](https://github.com/Haselnussbomber/HaselTweaks/files/10414031/dalamud.log)
[dalamud_appcrash_20230113_123800_780_28816.log](https://github.com/Haselnussbomber/HaselTweaks/files/10414032/dalamud_appcrash_20230113_123800_780_28816.log)

No other plugins enabled except HaselTweaks. Crashes as soon as armory chest is opened.

**Comment by Haselnussbomber** [comment]
I've been following the discussions in the Dalamud devs discord server and they are currently working on their SigScanner (staging [235137c](https://github.com/goatcorp/Dalamud/commit/235137c)), which is misbehaving. We will have to wait. 🤷‍♂️

Official status is:
> Franz — Today at 10:43 AM
> Dalamud will need to be fixed before it can be injected after FFXIV Patch 6.3 Hotfix. Testing will resume after that.

**Comment by kynetical** [comment]
Yep acknowledged. I will test again once the public test release is out.

**Comment by Haselnussbomber** [comment]
Found out that it was indeed something I caused in v0.7.7. The plugin caches the offsets in the configuration file, but clearing the old ones after an update didn't work, so everything pointed to the wrong address.

I pushed out v0.7.8, which should fix it.
If you're still having issues, because the plugin already scanned the addresses for the games hotfix, please close the game, open `%APPDATA%\XIVLauncher\pluginConfigs\HaselTweaks.json` and clear the value of "SigCacheVersion" (so the line is like `"SigCacheVersion": "",`), save the file and start the game again.
That should force the plugin to re-scan the addresses. 🙂

**Comment by kynetical** [comment]
Yep confirmed fixed for me with v0.7.9

Thanks so much for the plugin and the quick fix!

**Comment by Haselnussbomber** [comment]
Sure thing! 😄👍
