### ISSUE TITLE
[Feature Suggestion]Portrait Helper to support copying from other players

### ISSUE THREAD

**Issue by beckyeeky** [Haselnussbomber/HaselTweaks#20]

**Comment by PantsuPartyy** [comment]
This would be really nice to have if possible!

**Comment by Haselnussbomber** [comment]
Hey, sorry I didn't respond here for so long. I was torn on the idea and still am, because people probably spend a lot of time creating their portraits, and it just feels wrong to me when people copy other people's portraits.

However, as a compromise, I've reworked the copy/paste buttons into an export/import feature in [v0.14.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.14.0) that allows you to share presets as a base64-encoded string with other people who also use HaselTweaks.

Regarding going frame-by-frame on the animation: It's not that easy. I've tried to add this with a slider using the function that sets the animation and its timestamp, but it resulted into flickering as the whole animation gets reloaded every time I called it. Also I didn't find a way to read how long an animation is yet, to set a max value on the slider. So this is unfortunately something I have to figure out first.

**Comment by Marxvee** [comment]
> Regarding going frame-by-frame on the animation: It's not that easy. I've tried to add this with a slider using the function that sets the animation and its timestamp, but it resulted into flickering as the whole animation gets reloaded every time I called it. Also I didn't find a way to read how long an animation is yet, to set a max value on the slider. So this is unfortunately something I have to figure out first.

If you ever get the animation timestamp edit working, is there a possibility you could also add editing preset data directly, at least for camera position/target coordinates?

**Comment by Haselnussbomber** [comment]
Alright, I've released [v0.14.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.14.1) with an Advanced Edit Mode to set the raw Camera Position/Target, Eye/Head Directions and the Animation Timestamp.
It's not perfect, but the best I could do right now. 🤓

By the way, I think the camera uses a [spherical coordinate system](https://en.wikipedia.org/wiki/Spherical_coordinate_system), but what do I know. Good luck with that, I guess. 🤷‍♂️
