### ISSUE TITLE
[Suggestion] Craft Quests

### ISSUE THREAD

**Issue by Alkeyd** [Haselnussbomber/HaselTweaks#36]
Would you be able to create a tweak so that when you hold shift or a similar key and click on the quest that asks for a craft item, it already opens the Craft log with the searched item?

![image](https://user-images.githubusercontent.com/94228374/224892803-2d059730-ae38-4932-b386-768dbf1acb73.png)

**Comment by Haselnussbomber** [comment]
I have been working on that for the last few days because this is something I wanted too.

Instead of figuring out how to handle those clicks, I decided to just automatically open the recipe when the quest progresses.
The server adds the materials to the inventory before progressing the quest, so I've hooked the quest update function and check if the new step needs an item. If it's craftable and all materials are in the inventory, the recipe will open.

There are still some things I need to work out:
- I'm not sure if I read the current quest step correctly.
- It currently only checks the materials for one item, even if the quest step requires you to craft multiple items. Not sure if I should check all or not.
- This currently works for any quest, not just daily quests. Not sure if this is a good or a bad thing yet.
- It opens the recipe for the current crafter job. If it's not a crafter job, it will probably open it for carpenter instead of listing all possible recipes. (Haven't tested it yet.)

I've added it as an experimental tweak called "Auto-open Recipe" in [v0.13](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.13.0).
Maybe someone will stumble upon some weird behavior that I need to fix. 🙂

**Comment by Alkeyd** [comment]
I did my Loporrits diaries and it was magnificent, I'll keep testing and any information I'll leave here!

**Comment by Taurenkey** [comment]
Hey, as someone that's literally just gone down this rabbit hole too, I thought I'd chime in.

> I'm not sure if I read the current quest step correctly.

For a bunch of quests, yea it will. However there's some quests where it will not line or bug out. This is more apparent with legacy content, such as Moogles or Ixal quests. 

> It currently only checks the materials for one item, even if the quest step requires you to craft multiple items. Not sure if I should check all or not.

There's only one beast tribe quest that asks you to craft more than 1 thing, and it's the last rank-up quest for Ixal. 

> This currently works for any quest, not just daily quests. Not sure if this is a good or a bad thing yet.

I think your mileage may vary for quests pre-Stormblood, SE changed the way they encoded the quest text with Namazu being the first crafting tribe to recieve the new format. 

I ultimately found the best solution was just to compile a manual list of QuestID and the corresponding recipe IDs for each job (that bit was easy as they all followed a simple pattern).

**Comment by Haselnussbomber** [comment]
@Taurenkey Haha, nice! Are you making a plugin out of this? Just asking before I put more work into this. 😅

> For a bunch of quests, yea it will. However there's some quests where it will not or bug out. This is more apparent with legacy content, such as Moogles or Ixal quests.
> [...]
> SE changed the way they encoded the quest text with Namazu being the first crafting tribe to recieve the new format.

Thats very interesting! I quickly checked the Ixal lua scripts, and they do indeed not return the item id in GetTodoArgs, which would make the tweak not to open the recipe. That makes things more difficult. Hmm. 🤔

> There's only one beast tribe quest that asks you to craft more than 1 thing, and it's the last rank-up quest for Ixal.

Sorry for not being more clear. Multiple items required on different steps is not what I meant. If the quest step requires you to craft 3 of an item, the tweak currently only checks the materials for 1 of those 3 items, not in total. This is quick and easy to fix, by just multiplying the required item quantity. I just forgot, but it's not a big deal.

> I ultimately found the best solution was just to compile a manual list of QuestID and the corresponding recipe IDs

Yeah. I really don't like hardcoding such values, because it would require me to adjust to changes, even if they are *very*, *very* rare.
But it seems to be the easiest solution considering the missing item ids from GetTodoArgs and the fact that there aren't that many daily quests.

**Comment by Taurenkey** [comment]
> Are you making a plugin out of this?

This feature specifically, no. But I make a crafting based plugin, so I wanted to do this feature for it. It's all on my github if you wanted a peek. 

>Sorry for not being more clear. Multiple items required on different steps is not what I meant. If the quest step requires you to craft 3 of an item, the tweak currently only checks the materials for 1 of those 3 items, not in total. This is quick and easy to fix, by just multiplying the required item quantity. I just forgot, but it's not a big deal.

I see, yea, I just do my implementation by just checking for the ingredient, but I have a window that pops up if it detects them for the users to click on.

> Yeah. I really don't like hardcoding such values, because it would require me to adjust to changes, even if they are very, very rare.
But it seems to be the easiest solution considering the missing item ids from GetTodoArgs and the fact that there aren't that many daily quests.

If it's worth anything, we only get 1 crafting tribe per expansion, so it's what, a 2 yearly update? At least I only have mine set for beast tribes, though I am going to be adding the Stormblood craft quests. Don't really know how I'd feel about doing it for every quest though, given you can just buy the result items.

**Comment by Haselnussbomber** [comment]
Ah, ok. I think it'll be sufficient if I add something for those old quests, where GetTodoArgs doesn't return the item id.

Besides, thats a lot of numbers in your [QuestList.cs](https://github.com/Taurenkey/Artisan/blob/main/Artisan/QuestSync/QuestList.cs), haha!
I think you can just look up the recipe by ItemResult column and the CraftType column to differentiate between jobs, so you only need a QuestID => ItemId dictionary.
The CraftType is basically ClassJobId - 8, see info in [AgentRecipeNote.cs](https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRecipeNote.cs#L19-L27) from ClientStructs or the sheets themselves. 😉

**Comment by Taurenkey** [comment]
I had done it manually for good reason, given that my first endeavour was actually the Moogle quests and the first go at it had the step you had to craft on return 255 instead of 4. Whilst I could have just put 1 recipe on the list and work out the job offset from that, I made it this way to make sure I got every recipe since the end of CRP leads into BSM. Plus it was easily done in Excel, so it wasn't any bother (and it makes it look super involved, just as a bonus!).

If you look elsewhere in my plugin, you'll see I do use CraftType to pull recipes for the right job, so I'm *very* intimate with all the functions to do with recipes lol.

But back to the problematic quests, I couldn't tell you how many of them there would be, I just changed my design choice from the first time I saw sequence 255 pop up. You can use my list if you want for the older quests, since all the work has been done lol, and it would give you everything you need for those ones in particular.

**Comment by Haselnussbomber** [comment]
All good. I was almost sure there was a reason for it. You obviously have more insight. 😄
As for sequence 255 (byte 0xFF), my understanding is that it is just an indication for being the last step of a quest.

I will definitely use your list when I go through the quests one by one! Thank you! 🙂

**Comment by Taurenkey** [comment]
> As for sequence 255 (byte 0xFF), my understanding is that it is just an indication for being the last step of a quest.

Well, that would make sense, but it was more like the 2nd last step it appeared on lol. I just didn't want to deal with steps when the only thing you need to know is if someone has the ingredients, since you can't really get them any other way. It was a bit like taking the long way for a shortcut, especially since I couldn't parse the item name from the step anyway.

**Comment by Haselnussbomber** [comment]
Sorry, I mixed things up.
The sequence 255 obviously indicates that it's the last sequence of a quest, not step (lines in the quest tracker).
As far as I understand, the number of steps of a sequence is given in the ToDoQty column of the Quest sheet, indexed by the index of where the sequence is in ToDoCompleteSeq.

Like,
```cs
var todoIndex = quest.ToDoCompleteSeq.IndexOf((byte)0xFF);
var todoCount = quest.ToDoQty[todoIndex];
```

A quick lookup shows that there are two quests, which have more than 1 step on sequence 255:
- 3 on 65777 (Lone Survivor from the Delivery Moogle Quests) 
- and 5 on 66090 (Harder than Rock from the Pugilist Quests).

As always, not sure if this is all correct. Just wanted to differentiate sequence and steps. 🤷‍♂️ 🙂

**Comment by Haselnussbomber** [comment]
Closing this. If there are any issues with the tweak, just open a new issue. 🙂
