### ISSUE TITLE
Quest emotes or quotes

### ISSUE THREAD

**Issue by Dedoooo** [Haselnussbomber/HaselTweaks#37]
I'm wondering if this is doable similarly to the crafting recipes? 
thought i'd suggest if it can be done without too much _Hassel_ :)

**Comment by Haselnussbomber** [comment]
I mean, automatically opening a recipe just saves a couple of clicks in the UI.
In my opinion, emoting or sending something in chat would be a bit too much, since not only will it be seen by others, but it also would complete quest objectives.
Sure it's a fine line, but at some point we're in the territory of botting and I'd rather not be a part of that.
So, sorry, but I'm not going to do that.
