### ISSUE TITLE
[Portrait Helper] Auto-update Portrait not working entirely as expected.

### ISSUE THREAD

**Issue by nullKomplex** [Haselnussbomber/HaselTweaks#42]
When updating a gearset and joining an instance the default portrait will be shown (accompanied with the appropriate warning).

However, changing to another job and back to the original job causes it to work/update as intended. (Clicking on the same job without switching does NOT work)

Is it possible to fix it so that one does not need to change jobs back and forth to update?

**Comment by Haselnussbomber** [comment]
Hmm, yeah, it's a little tricky and I probably didn't think it through.

As you know, the tweak generates the gearset hash, which is saved in the portrait, when you update the gearset.
It goes through each slot and checks the glamours, but if a glamour plate is linked to the gearset, the glamour plate data takes priority.
Basically like this (pseudocode):
```cs
var glamourPlate = gearset.GlamourPlate;
var itemIds = new List<uint>();

foreach (var slot in ItemSlots)
{
  var gearsetSlot = gearset.Slots[slot];
  var id = gearsetSlot.ItemId;

  if (gearsetSlot.GlamourId != 0)
    id = gearsetSlot.GlamourId;

  if (glamourPlate != null && glamourPlate[slot].ItemId != 0)
    id = glamourPlate[slot].ItemId;

  itemIds.add(id);
}

// generate hash with itemIds
```

That means: if the gearset is linked with a glamour plate, you equip a new item and update your gear set, it will generate the hash with the item id of the item in the glamour plate, which obviously doesn't match the item, since you didn't apply the glamour plate before updating the gearset.
And this is why the portrait works when you switch back and forth - you're applying the glamour plate to the gearset when you equip a gearset.

I barely run into this problem, since I'm always applying the glamour plate after changing an item, because I don't want to look like a goofus. 🤷‍♂️ So... i don't know. Maybe thats how the game already does it?

**Comment by Haselnussbomber** [comment]
I've removed the option from the plugin. Ultimately it didn't do anything and I'm very sorry. 😞🙏

The portrait is sent to the server, whenever you save it in the editor, which includes a checksum of the item appearances (as described above). My tweak never sent the new hash to the server and I don't plan to implement that.

I've always wondered how infrequently this happens to me, but I've come to the conclusion that most of the time I apply the glamour plate to my gearset after changing an item, which keeps the portrait working since the hash still matches the one generated with the glamour plate item ids.

I'll tinker around and see if I can make a tweak that equips the gearset after hitting the update button to ensure the glamour plate is re-applied.

**Comment by nullKomplex** [comment]
Okay sorry, I've actually not been using this tweak and have been instead writing for someone less ticket-inclined.

I think there's a minor disconnect in what we expected the plugin to do and what it actually does. A few points to that:

1. The original ticket was tested entirely without having glamour plates linked to gear sets.
2. Testing with glamour plates linked does re-equip the gearset, reapplying the plate, but still doesn't seem to work (portrait is still default).
3. Previous behavior is now _worse_ when not using glamour plates linked to gear sets.

So in the original ticket the full STR is as follows:

1. Equip Monk gear set (no linked glamour plate).
2. Use a glamour plate to apply change in glamour.
3. Update gearset.
4. Enter Sastasha solo.
5. Observe Instant Portrait popup.
6. Leave Sastasha.
7. Change to Reaper.
8. Change back to Monk.
9. Enter Sastasha Solo.
10. Observe Instant Portrait popup.

In the original ticket, using 5ed8456bf690ddf5c16a21160e09e7b306140547, step 4 would result in a default portrait and step 9 would result in a correct instant portrait. As of the latest version (15d901475789b31984c7d6e657aa3d516561bf8a) 9 is now a default portrait again.



To state it plainly, we expected the plugin to automatically adjust the instant portrait whenever our appearance changed. Most notably this was when using a glamour plate. The original iteration of this tweak nearly nailed this behavior. It simply required you to change jobs back and forth after updating your gearset. This version does not have that behavior, and even though it will reapply the linked glamour plate if one exists, the instant portrait is still not being updated properly and a default portait is being shown.

It's possible that what we were seeing in the original iteration was actually unintended, but ironically it's closer to what we actually want as a portrait auto-updater, as we would prefer not to link glamour plates to gear sets.

**Comment by Haselnussbomber** [comment]
> 1. The original ticket was tested entirely without having glamour plates linked to gear sets.

Ah, to be honest I didn't even think of not using glamour plates when I made the second version.

> 2. Testing with glamour plates linked does re-equip the gearset, reapplying the plate, but still doesn't seem to work (portrait is still default).

Then the glamour plate might not cover all the things.

The equipped appearance has to *exactly* match the one saved in the portrait (as in the checksum has to match).
This includes the item ids (or their glamour ids, or whatever the slot is set to in the linked glamour plate), the corresponding stain (dye of an item), the mainhand and headgear visibility and if the visor is closed or not.

So I just tried it like this:
- I unlinked the glamour plate from the gearset
- Equipped a random earring, which looks entirely different
- Entered Sastasha
- The portrait was reset to default
- Left Sastasha
- Applied my glamour plate
  - still not linked in the gearset
  - made the earring invisible (The Emperor's New Earrings in the glamour plate)
  - made me match the appearance as saved in the portrait
- Entered Sastasha
- The portrait was shown

This is why I came up with the new version, which re-equips the gearset to reapply the glamour plate (preferably with all slots set to something, except offhand when not applicable) to ensure the appearance matches.

> To state it plainly, we expected the plugin to automatically adjust the instant portrait whenever our appearance changed. [...] The original iteration of this tweak nearly nailed this behavior. It simply required you to change jobs back and forth after updating your gearset.

Yeah, I mean, that's what I had in mind when I made the first version of the tweak, but how it possibly worked better I absolutely can not explain.
My old version did not send *any* packets with the updated checksum to the server (at least I don't recall it sending any packets when I modified it in the local portrait data), so I can only assume that one of the other variables (stain, visibility or visor state) in the checksum didn't match when you tested it. I don't know.
I also can't imagine, that the server requests everyones portraits again when joining an instance. Why else would it send the portrait to the server, when you save it.

So I'm afraid I'm not going to dig deeper into this. It's very time consuming and (sorry to say) I have a solution for it, though it may not be the best one for you (or your friend).
It's certainly a problem many players have with how often I see the default portrait. Hopefully SE will change how it works some time soon, preferably saving the appearance in the portraits directly, not just the checksum.
