### ISSUE TITLE
FPS clips into Where Am I Again location with sufficiently long location name.

### ISSUE THREAD

**Issue by HimitsuYami** [Haselnussbomber/HaselTweaks#43]
Title. Got yelled at in the Dalamud discord for not realizing this was part of a 3pp so I wanted to bring it up directly. But if the server info bar gets long enough, first there's a lack of a space between "fps" and the first character of Where Am I Again, then with particularly long names (in terms of how far along your screen) it eventually starts to clip into itself as shown here.
![image](https://user-images.githubusercontent.com/21053554/235826166-f032bada-1739-410e-afdd-93ff3f3e6cc9.png)

**Comment by Haselnussbomber** [comment]
Sorry this happened to you! They tend to be quite harsh when a third party plugin is involved. 😞

Yet, I'm not really sure what I could do there. I'm quite literally giving it a stinky ass normal C# string, so this is more like an issue of the DtrBar in Dalamud, or an element in between those two is misbehaving.

Can you try to reorder the elements in the "Server Info Bar" tab in the Dalamud settings?
![ffxiv_dx11_2023-05-03_10-34-40](https://user-images.githubusercontent.com/96642047/235868070-d1db5228-a761-4bcf-ae0b-e14cdc1d0538.png)
Maybe you can find out which element causes the problem or - if not - at least reorder it so that it shows correctly.

**Comment by HimitsuYami** [comment]
It's not an issue with this plugin it seems. Managed to recreate it with all 3pp disabled and am getting help from the Discord

**Comment by HimitsuYami** [comment]
By all means, we can close the issue here, thanks for your time!
