### ISSUE TITLE
tweak to enable keybind toggle for armory chest -> return to inventory context menu option

### ISSUE THREAD

**Issue by Dedoooo** [Haselnussbomber/HaselTweaks#44]
This would make cleaning inventories much easier!

**Comment by Haselnussbomber** [comment]
Hey there,

thanks for the suggestion, but in general I don't really take new tweak requests here, since this plugin consists of tweaks/solutions that I wanted and built for myself.

Also, this is not something I would need, because if you go to Character Configuration -> Item Settings, you can uncheck "Store all newly obtained items in the Armoury Chest.", so they go straight into your inventory.

This pretty much solved the problem with the cumbersome armoury chest for me. It only stores items that I actually use in my gearsets, so I rarely have to move things around. Makes it a lot cleaner, in my eyes.
You might want to give it a try. 🙂

<details>
<summary>Click here for an image of the config option from reddit</summary>
<img src="https://i.redd.it/6yd2rshojem31.png"/>
</details>

If this is not a solution for you, I would encourage you to suggest this in the Dalamuds Discord `#new-plugin-ideas` channel or in their [Plugin suggestions](https://github.com/goatcorp/suggestions/issues) repository. It could be that someone will add a solution for this in SimpleTweaks, although I doubt it, since it's such a non-issue with the setting unchecked.

That said, I'm sorry, but I'm closing this as not planned.
