### ISSUE TITLE
Advanced Edit mode - Window in the way

### ISSUE THREAD

**Issue by Theletha** [Haselnussbomber/HaselTweaks#47]
Hi! Love your plugin and the plate save. I'm baffled that there isn't more plugins that have that yet.

I have this problem that when i want to use the advanced edit mode for portraits it covers up the portrait so its really hard to see the changes in real time i have to keep closing it and opening it. 

would be great if the window could move more to the left or have a button to detach the window. Not sure what would be easiest.

https://i.imgur.com/BFUINRF.jpeg

**Comment by Haselnussbomber** [comment]
Heya,

thanks for using it. 🙂

So, yeah... The problem occurs when you've set the Global Font Scale in Dalamud higher than 12pt (Dalamud Settings -> Look & Feel tab). I'm not sure how to adapt to that right now. Might have to rework my whole UI for this.

This is how it looks like on 12pt, fitting perfectly:

![Screenshot](https://github.com/Haselnussbomber/HaselTweaks/assets/96642047/92b81da2-0f09-46d9-bc59-4f08a20ab393)

Maybe you can change the scale for the time you're in the advanced edit mode for now until I find time to fix this. Sorry!

**Comment by Theletha** [comment]
ok thanks for the info ill do that in the meantime!

**Comment by Haselnussbomber** [comment]
I've released [v15.1.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v15.1.0), which adds global font scale support throughout the plugin. 🙂

I implemented your suggestion for the Portrait Helper overlays, since they were already windows under the hood, just had to tweak the closing mechanism a bit.
They will now simply open as windows instead, if the scaling is greater than 12pt. 😉
