### ISSUE TITLE
[Bug] Crash Report

### ISSUE THREAD

**Issue by TheOddball** [Haselnussbomber/HaselTweaks#54]
Log: [dalamud_appcrash_20230730_131458_771_15584.log](https://github.com/Haselnussbomber/HaselTweaks/files/12210049/dalamud_appcrash_20230730_131458_771_15584.log)
Memory Dump: [dalamud_appcrash_20230730_131458_771_15584.zip](https://github.com/Haselnussbomber/HaselTweaks/files/12210050/dalamud_appcrash_20230730_131458_771_15584.zip)

What I did to cause crash:
I changed aetherytes using Lifestream, and closed some vanilla menus (crafting log + inventory).

**Comment by Haselnussbomber** [comment]
I've seen crashes like this before, but every time the address is somewhat unrelated to the function I'm hooking. It's the same hook SimpleTweaks uses to detect when windows are closed. It's very difficult to say what exactly happend.
Sorry, I can't do anything about this right now, but I'll try to find another way to do this (soon).
Thanks for reporting though! 🙂

**Comment by Haselnussbomber** [comment]
Alright, I just released v16 in which I removed the hooks and wrote my own window open/close detection. Doing it the old way of comparing lists. So, if you encounter this crash again, it's probably/hopefully not because of my plugin. :joy:

I'll close this issue now, but if it happens again and it says HaselTweaks, then don't hesitate to comment here. 🙂

**Comment by TheOddball** [comment]
Thank you so much for the quick fix. Your plugin is amazing, keep up the good work!
P.S.: Your implementation of imgui is amazing ♥
