### ISSUE TITLE
[Request] Custom Chat Channel Prefixes

### ISSUE THREAD

**Issue by ZohiDev** [Haselnussbomber/HaselTweaks#57]
Hi! I was wondering if a tweak to set custom chat channel prefixes would be possible. For example:

Current: `[CWLS1]<User Name> Message` 
Proposed: `[C1]<User Name> Message`

Thanks for your consideration and work on this plugin!

**Comment by Haselnussbomber** [comment]
I never closed the issue, because I wanted to add it eventually.
Well today is the day! I finally added it. It's part of [v21.0.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v21.0.0). 🙂
Sorry it took so long! There were a lot of unknowns back then, but we finally have the technology. 🎉
