### ISSUE TITLE
Auto music 

### ISSUE THREAD

**Issue by Samidaro** [Haselnussbomber/HaselTweaks#6]
hi,
love the plugin. Any chance of adding "auto turn on music in boss fights only". Similar to the cutscene one. Thanks

**Comment by Haselnussbomber** [comment]
Hey,

sorry for the late reply and sorry, but no.

The `Forced Cutscene Music` tweak was something I built because I wanted to get rid of an annoyance.
I often forget to turn background music on before the cutscene starts. The problem is, that the games audio settings aren't accessible (because esc = skip cutscene dialogue) and the `/bgm` chat command doesn't work during cutscenes either.

(As a sidenote: the tweak doesn't even work for all cutscenes, just the ones started by the games lua scripts, I think. It works well enough for me to not look into it any further.)

During boss fights however the `/bgm` command does work. I know this is not the answer you're looking for, because you want a plugin to handle this automatically, but I recommend a macro with `/bgm` bound to ctrl+m or something similar. Thats how I have it at least.

Also, as far as I'm aware, while it's possible to detect whether the character is in combat or not (any fight) it's not possible to easily detect when a boss fight specifically starts or ends.

Anyhow, this plugin is just a collection of tweaks that I basically wrote for myself. I never planned on doing requests and adding things I don't need. Otherwise I'd have to maintain code I don't care about and so on and so forth. I hope you understand.

You could try your luck at SimpleTweaks or on the Dalamud Discord Server (#plugin-suggestions). Maybe you can find someone there who will work on this. 🙂
