### ISSUE TITLE
[Bug] Enhanced Isleworks Agenda Crash

### ISSUE THREAD

**Issue by Slightlyxz** [Haselnussbomber/HaselTweaks#70]
When using the Enhanced Isleworks Agenda tweak, you crash to desktop as soon as you type inside the search field.
I seem to not be the only one with the issue, as I have seen others mention it on the puni.sh discord server.

There seems to be no error in the dalamud.log file either, it just straight up crashes to desktop.

**Comment by Haselnussbomber** [comment]
Hey, sorry for the late response (timezones and all).

I'm not sure. Are you on rank 18 yet? I guess not and assume it has something to do with not having all craftable items unlocked.
Since I am already on rank 18, it makes it really hard to figure out why it happens, because for me all values are present.
I'm not crashing on the german nor the english client.
Not sure how to debug this now.

**Comment by Haselnussbomber** [comment]
I've released [v19.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v19.0.1) with a possible fix. Please try it out if you find time. 🙂

**Comment by Slightlyxz** [comment]
Just tried and the update fixed it, not crashing anymore.
Weirdly enough I was already rank 19/20 when I was crashing yesterday.

Thanks for the quick fix!
