### ISSUE TITLE
Crash to Desktop with Scrollable tabs in the Character menu

### ISSUE THREAD

**Issue by Lyli-01** [Haselnussbomber/HaselTweaks#72]
Hello! Noticed this issue after the most recent update of HaselTweaks (v19.0.5):

1. Go in the Character Menu.
2. Go to the Reputation tab.
3. Scroll to cycle through the tabs (if any) to go further than the Endwalker one.
4. Game will freeze for a moment before crashing to desktop with no errors.

Happens both if you have all expansion tabs or none at all (tested on an alt). Isolated HaselTweaks in a collection and repro'ed with it being the only plugin active as well.

Hope it helps!

**Comment by Haselnussbomber** [comment]
Heya,

Hmm, I'm not sure whats going on with your crash.

I tried scrolling super fast and changing the inverted scroll setting, but either way I can't get my game to crash.
The plugin reads how many entries the list should have and clamps the values correctly to prevent me from scrolling out of bounds.

Was this a problem in v19.0.4 too? I'm asking because there were no changes to the Scrollable Tabs tweak in v19.0.5.

I'm really confused how this is possible. Are you on Dalamud 9.0.0.9? 🤔

**Comment by Lyli-01** [comment]
Can confirm Dalamud 9.0.0.9. I don't recall getting the crash prior but I also haven't been in my Reputation tab in a couple of months since finishing my last tribe to max.

...And after repro'ing it 4/4 this morning and taking a small break, now it's not doing it anymore. :| Wellp. Should I close the issue until I/someone else finds better repro steps?

**Comment by Haselnussbomber** [comment]
(Sorry for the late response, I had dinner. 😊)

Well, sometimes that's just how it is. Maybe computers have bad days too. 😅
Yeah, I guess we can close it. If you run into this problem again, don't hesitate to reply on the closed issue. 🙂
