### ISSUE TITLE
[Bug] Class Switcher

### ISSUE THREAD

**Issue by E-Ballard** [Haselnussbomber/HaselTweaks#8]
Maybe something changed in the code, it instantly crashes to desktop on hover of any of the classes with the option turned on.

**Comment by Haselnussbomber** [comment]
Thanks for notifying. FFXIVClientStructs had a breaking change that got pushed with a Dalamud update.
I adjusted the code and released an update ([v0.2.4](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.2.4)). Shouldn't crash anymore. 🙂

**Comment by skylargraves** [comment]
This still crashes my game btw. Uninstalled and reinstalled. Did as much troubleshooting as I could and still happened. I run on a Mac.

**Comment by Haselnussbomber** [comment]
@skylargraves Are you using Dalamud v6.4.0.31 and HaselTweaks v0.2.4?
And do you have the "Character Window Job Switcher" enabled in SimpleTweaks? If so, disable it there and restart the game, because it's incompatible with my tweak.
Other than that, I have no clue. Maybe you can find something in the dalamud log files?

**Comment by skylargraves** [comment]
heh no joke it was doing up until yesterday. Tried again to get it to throw the error and catch the log and it's working. I was updated on both and had job switcher on simple tweaks turned off. I'm guessing something JUST updated (dalamud or a conflicting app) and now it's working as a result. ty for the response
