### ISSUE TITLE
[Portrait Helper] [Request] Increase decimal places in the timestamp

### ISSUE THREAD

**Issue by beckyeeky** [Haselnussbomber/HaselTweaks#92]
I have a specific requirement for the precision of timestamps used in animating manually created portraits. 
For instance, we manipulate the animation to pause at very precise moments to create an portrait where the character blinks upon opening the portrait. Currently, this level of precision can be achieved by manually editing the data to be imported or exporting from a manually paused portait, as shown with the example: `SFRQUwEAGTHEsAc8ADxMMJ0qyyYAPAMAyDIAmnktQwAAAAAA+TQWsSMzvP/E/8T/Mhz/SXcAfwBPAA==`
It is for Au Ra Raen with Battle Stance.

Please kindly consider adding support of manual input of timestamps with three decimal places for such purpose.

**Comment by Haselnussbomber** [comment]
You can double-click on the slider to enter timestamps manually.
The display of the value is just rounded to 2 decimal points, but you should be able to enter more.

**Comment by beckyeeky** [comment]
Thanks!
For those who are interested, I did more experiments and it turns out the precision for pausing game animations is limited to 5ms. This means if the character doesn't blink at 173.745 seconds, no matter how precise the timestamp is, it won't achieve the blinking effect. 
It appears that a timestamp where the blink animation is longer— for me at least long enough to silently mumble a two-syllable word—to ensure the blinking occurs.

**Comment by Haselnussbomber** [comment]
The animation timestamp slider uses frames as unit, not seconds.
As far as I know, all animations in the game are in 30 frames per second, but the game interpolates in between each frame. I don't know how precise the games interpolation is.
I just found 3 decimals is too slow to slide for most animations, which is why I settled on 2, but I could make it 3 if the animation is under 100 frames long or something.
