### ISSUE TITLE
Cast Bar Aetheryte Names

### ISSUE THREAD

**Issue by Scrxtchy** [Haselnussbomber/HaselTweaks#97]
This seems to have some issues with being a bit too greedy.
Interacting with objects in Haukke Manor displayed undesired destination text

![image](https://github.com/Haselnussbomber/HaselTweaks/assets/12771982/98efbefb-09ea-42e9-9924-438b6ed8c862)

**Comment by Haselnussbomber** [comment]
Interesting. Thanks for reporting!
It could certainly be that the cast bar can be opened via different calls too.

I added an internal reset after the spell name ("Teleport") was replaced with the aetheryte name, so that it can't occur on subsequent casts. That reset is also called when the client changes zones, just to be sure.

Please update to [v23.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v23.0.1).
If the issue is not fixed, just comment here again! 🙂
